### ISSUE TITLE
Can't open KUI settings while AzeriteUI pluggin is enabled.

### ISSUE THREAD

**Issue by nicholastrunkey** [AzeriteTeam/AzeriteUI_KuiNameplates#2]
While the AzeriteUI pluggin is enabled, I can't open the regular KUI nameplate settings.

KuiNamePlate version: 2.25.4
KuiNameplates_AzeriteUI version: 1.0.4

Tested on up to date Win10 with WoW retail 8.3.

**Comment by goldpaw** [comment]
Actually no a bug. Those settings only apply to their theme, this one doesn't come with any.
